### ISSUE TITLE
Missing python attribute bug

### ISSUE THREAD

**Issue by finnless** [finnless/waam#26]
```
response:
 {
  "message": "# Header 1\n\n$$ y = mx + b $$\nIn line $x$ like this"
}
2023-04-15 18:08:27.566 Uncaught app exception
Traceback (most recent call last):
  File "/Users/nolan/.pyenv/versions/3.9.9/envs/waam/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/nolan/Documents/5chack/waam/app.py", line 148, in <module>
    if json_output["python"] != "":
KeyError: 'python'
```

**Comment by finnless** [comment]
Would be closed by #29 because not using #18 json approach
